# For week 1 strech excercise.

on: push
jobs:
  build-container: 
    name: Login to Docker Hub
    runs-on: linux
    steps:
      - name: Check out code
        uses: checkout/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_KEY }} 
